print("Este é um código para a atividade do professor André")
numero1 = 5 + 5
print("Esta atividade tem que ter 10 linhas e commits para cada uma")
print("Linha número 4 do código!")
print("Esta linha vai para o quinto commit")
print("Eu sou o vitor soster felix")
print("Eu gosto de tekken")
print("Eu toco piano")
print("Atividade grande")
print("Atividade acabou")
print("aqui teremos outra parte da atividadde onde será feito um merge em uma branch nova!")
print("agora sim o commit da atividade está certo")
print("Também haverá merge")